before:
  hooks:
    - ./scripts/completions.sh
    - ./scripts/manpages.sh

builds:
  - id: darwin-amd64-rdp
    binary: infisical
    ldflags:
      - -X github.com/Infisical/infisical-merge/packages/util.CLI_VERSION={{ .Version }}
      - -X github.com/Infisical/infisical-merge/packages/telemetry.POSTHOG_API_KEY_FOR_CLI={{ .Env.POSTHOG_API_KEY_FOR_CLI }}
    flags:
      - -trimpath
      - -tags=rdp
    env:
      - CGO_ENABLED=1
      - 'CGO_LDFLAGS=-L packages/pam/handlers/rdp/native/target/x86_64-apple-darwin/release'
    goos:
      - darwin
    goarch:
      - amd64

  - id: darwin-arm64-rdp
    binary: infisical
    ldflags:
      - -X github.com/Infisical/infisical-merge/packages/util.CLI_VERSION={{ .Version }}
      - -X github.com/Infisical/infisical-merge/packages/telemetry.POSTHOG_API_KEY_FOR_CLI={{ .Env.POSTHOG_API_KEY_FOR_CLI }}
    flags:
      - -trimpath
      - -tags=rdp
    env:
      - CGO_ENABLED=1
      - 'CGO_LDFLAGS=-L packages/pam/handlers/rdp/native/target/aarch64-apple-darwin/release'
    goos:
      - darwin
    goarch:
      - arm64

archives:
  - files:
      - README*
      - LICENSE*
      - manpages/*
      - completions/*

# Append to the release draft created by the ubuntu goreleaser job.
release:
  replace_existing_draft: false
  mode: append

checksum:
  name_template: "checksums-darwin.txt"

snapshot:
  name_template: "{{ .Version }}-devel"

brews:
  - name: infisical
    tap:
      owner: Infisical
      name: homebrew-get-cli
    commit_author:
      name: "Infisical"
      email: ai@infisical.com
    folder: Formula
    homepage: "https://infisical.com"
    description: "The official Infisical CLI"
    install: |-
      bin.install "infisical"
      bash_completion.install "completions/infisical.bash" => "infisical"
      zsh_completion.install "completions/infisical.zsh" => "_infisical"
      fish_completion.install "completions/infisical.fish"
      man1.install "manpages/infisical.1.gz"
  - name: "infisical@{{.Version}}"
    tap:
      owner: Infisical
      name: homebrew-get-cli
    commit_author:
      name: "Infisical"
      email: ai@infisical.com
    folder: Formula
    homepage: "https://infisical.com"
    description: "The official Infisical CLI"
    install: |-
      bin.install "infisical"
      bash_completion.install "completions/infisical.bash" => "infisical"
      zsh_completion.install "completions/infisical.zsh" => "_infisical"
      fish_completion.install "completions/infisical.fish"
      man1.install "manpages/infisical.1.gz"
