// Package client provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package client

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for GetApiV1ProjectsParamsIncludeRoles.
const (
	False GetApiV1ProjectsParamsIncludeRoles = "false"
	True  GetApiV1ProjectsParamsIncludeRoles = "true"
)

// Defines values for GetApiV1ProjectsParamsType.
const (
	GetApiV1ProjectsParamsTypeCertManager    GetApiV1ProjectsParamsType = "cert-manager"
	GetApiV1ProjectsParamsTypeKms            GetApiV1ProjectsParamsType = "kms"
	GetApiV1ProjectsParamsTypePam            GetApiV1ProjectsParamsType = "pam"
	GetApiV1ProjectsParamsTypeSecretManager  GetApiV1ProjectsParamsType = "secret-manager"
	GetApiV1ProjectsParamsTypeSecretScanning GetApiV1ProjectsParamsType = "secret-scanning"
	GetApiV1ProjectsParamsTypeSsh            GetApiV1ProjectsParamsType = "ssh"
)

// Defines values for PostApiV1ProjectsJSONBodyType.
const (
	PostApiV1ProjectsJSONBodyTypeCertManager    PostApiV1ProjectsJSONBodyType = "cert-manager"
	PostApiV1ProjectsJSONBodyTypeKms            PostApiV1ProjectsJSONBodyType = "kms"
	PostApiV1ProjectsJSONBodyTypePam            PostApiV1ProjectsJSONBodyType = "pam"
	PostApiV1ProjectsJSONBodyTypeSecretManager  PostApiV1ProjectsJSONBodyType = "secret-manager"
	PostApiV1ProjectsJSONBodyTypeSecretScanning PostApiV1ProjectsJSONBodyType = "secret-scanning"
	PostApiV1ProjectsJSONBodyTypeSsh            PostApiV1ProjectsJSONBodyType = "ssh"
)

// Defines values for PostApiV3AuthSelectOrganizationJSONBodyUserAgent.
const (
	Cli PostApiV3AuthSelectOrganizationJSONBodyUserAgent = "cli"
)

// PostApiV1AdminSignupJSONBody defines parameters for PostApiV1AdminSignup.
type PostApiV1AdminSignupJSONBody struct {
	Email     openapi_types.Email `json:"email"`
	FirstName string              `json:"firstName"`
	LastName  *string             `json:"lastName,omitempty"`
	Password  string              `json:"password"`
}

// GetApiV1ProjectsParams defines parameters for GetApiV1Projects.
type GetApiV1ProjectsParams struct {
	IncludeRoles *GetApiV1ProjectsParamsIncludeRoles `form:"includeRoles,omitempty" json:"includeRoles,omitempty"`
	Type         *GetApiV1ProjectsParamsType         `form:"type,omitempty" json:"type,omitempty"`
}

// GetApiV1ProjectsParamsIncludeRoles defines parameters for GetApiV1Projects.
type GetApiV1ProjectsParamsIncludeRoles string

// GetApiV1ProjectsParamsType defines parameters for GetApiV1Projects.
type GetApiV1ProjectsParamsType string

// PostApiV1ProjectsJSONBody defines parameters for PostApiV1Projects.
type PostApiV1ProjectsJSONBody struct {
	HasDeleteProtection *bool   `json:"hasDeleteProtection,omitempty"`
	KmsKeyId            *string `json:"kmsKeyId,omitempty"`

	// ProjectDescription An optional description label for the project.
	ProjectDescription *string `json:"projectDescription,omitempty"`

	// ProjectName The name of the project to create.
	ProjectName             string `json:"projectName"`
	ShouldCreateDefaultEnvs *bool  `json:"shouldCreateDefaultEnvs,omitempty"`

	// Slug An optional slug for the project.
	Slug *string `json:"slug,omitempty"`

	// Template The name of the project template, if specified, to apply to this project.
	Template *string                        `json:"template,omitempty"`
	Type     *PostApiV1ProjectsJSONBodyType `json:"type,omitempty"`
}

// PostApiV1ProjectsJSONBodyType defines parameters for PostApiV1Projects.
type PostApiV1ProjectsJSONBodyType string

// PostApiV3AuthSelectOrganizationJSONBody defines parameters for PostApiV3AuthSelectOrganization.
type PostApiV3AuthSelectOrganizationJSONBody struct {
	OrganizationId string                                            `json:"organizationId"`
	UserAgent      *PostApiV3AuthSelectOrganizationJSONBodyUserAgent `json:"userAgent,omitempty"`
}

// PostApiV3AuthSelectOrganizationJSONBodyUserAgent defines parameters for PostApiV3AuthSelectOrganization.
type PostApiV3AuthSelectOrganizationJSONBodyUserAgent string

// PostApiV1AdminSignupJSONRequestBody defines body for PostApiV1AdminSignup for application/json ContentType.
type PostApiV1AdminSignupJSONRequestBody PostApiV1AdminSignupJSONBody

// PostApiV1ProjectsJSONRequestBody defines body for PostApiV1Projects for application/json ContentType.
type PostApiV1ProjectsJSONRequestBody PostApiV1ProjectsJSONBody

// PostApiV3AuthSelectOrganizationJSONRequestBody defines body for PostApiV3AuthSelectOrganization for application/json ContentType.
type PostApiV3AuthSelectOrganizationJSONRequestBody PostApiV3AuthSelectOrganizationJSONBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// PostApiV1AdminSignupWithBody request with any body
	PostApiV1AdminSignupWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostApiV1AdminSignup(ctx context.Context, body PostApiV1AdminSignupJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostApiV1AuthToken request
	PostApiV1AuthToken(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiV1Projects request
	GetApiV1Projects(ctx context.Context, params *GetApiV1ProjectsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostApiV1ProjectsWithBody request with any body
	PostApiV1ProjectsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostApiV1Projects(ctx context.Context, body PostApiV1ProjectsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostApiV3AuthSelectOrganizationWithBody request with any body
	PostApiV3AuthSelectOrganizationWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostApiV3AuthSelectOrganization(ctx context.Context, body PostApiV3AuthSelectOrganizationJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) PostApiV1AdminSignupWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiV1AdminSignupRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiV1AdminSignup(ctx context.Context, body PostApiV1AdminSignupJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiV1AdminSignupRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiV1AuthToken(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiV1AuthTokenRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiV1Projects(ctx context.Context, params *GetApiV1ProjectsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiV1ProjectsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiV1ProjectsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiV1ProjectsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiV1Projects(ctx context.Context, body PostApiV1ProjectsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiV1ProjectsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiV3AuthSelectOrganizationWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiV3AuthSelectOrganizationRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiV3AuthSelectOrganization(ctx context.Context, body PostApiV3AuthSelectOrganizationJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiV3AuthSelectOrganizationRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewPostApiV1AdminSignupRequest calls the generic PostApiV1AdminSignup builder with application/json body
func NewPostApiV1AdminSignupRequest(server string, body PostApiV1AdminSignupJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostApiV1AdminSignupRequestWithBody(server, "application/json", bodyReader)
}

// NewPostApiV1AdminSignupRequestWithBody generates requests for PostApiV1AdminSignup with any type of body
func NewPostApiV1AdminSignupRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/admin/signup")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostApiV1AuthTokenRequest generates requests for PostApiV1AuthToken
func NewPostApiV1AuthTokenRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/auth/token")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetApiV1ProjectsRequest generates requests for GetApiV1Projects
func NewGetApiV1ProjectsRequest(server string, params *GetApiV1ProjectsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/projects")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.IncludeRoles != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "includeRoles", runtime.ParamLocationQuery, *params.IncludeRoles); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Type != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "type", runtime.ParamLocationQuery, *params.Type); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostApiV1ProjectsRequest calls the generic PostApiV1Projects builder with application/json body
func NewPostApiV1ProjectsRequest(server string, body PostApiV1ProjectsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostApiV1ProjectsRequestWithBody(server, "application/json", bodyReader)
}

// NewPostApiV1ProjectsRequestWithBody generates requests for PostApiV1Projects with any type of body
func NewPostApiV1ProjectsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/projects")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostApiV3AuthSelectOrganizationRequest calls the generic PostApiV3AuthSelectOrganization builder with application/json body
func NewPostApiV3AuthSelectOrganizationRequest(server string, body PostApiV3AuthSelectOrganizationJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostApiV3AuthSelectOrganizationRequestWithBody(server, "application/json", bodyReader)
}

// NewPostApiV3AuthSelectOrganizationRequestWithBody generates requests for PostApiV3AuthSelectOrganization with any type of body
func NewPostApiV3AuthSelectOrganizationRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v3/auth/select-organization")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// PostApiV1AdminSignupWithBodyWithResponse request with any body
	PostApiV1AdminSignupWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiV1AdminSignupResponse, error)

	PostApiV1AdminSignupWithResponse(ctx context.Context, body PostApiV1AdminSignupJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiV1AdminSignupResponse, error)

	// PostApiV1AuthTokenWithResponse request
	PostApiV1AuthTokenWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*PostApiV1AuthTokenResponse, error)

	// GetApiV1ProjectsWithResponse request
	GetApiV1ProjectsWithResponse(ctx context.Context, params *GetApiV1ProjectsParams, reqEditors ...RequestEditorFn) (*GetApiV1ProjectsResponse, error)

	// PostApiV1ProjectsWithBodyWithResponse request with any body
	PostApiV1ProjectsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiV1ProjectsResponse, error)

	PostApiV1ProjectsWithResponse(ctx context.Context, body PostApiV1ProjectsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiV1ProjectsResponse, error)

	// PostApiV3AuthSelectOrganizationWithBodyWithResponse request with any body
	PostApiV3AuthSelectOrganizationWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiV3AuthSelectOrganizationResponse, error)

	PostApiV3AuthSelectOrganizationWithResponse(ctx context.Context, body PostApiV3AuthSelectOrganizationJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiV3AuthSelectOrganizationResponse, error)
}

type PostApiV1AdminSignupResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Message      string `json:"message"`
		New          string `json:"new"`
		Organization struct {
			AllowSecretSharingOutsideOrganization *bool               `json:"allowSecretSharingOutsideOrganization"`
			AuthEnforced                          *bool               `json:"authEnforced"`
			BlockDuplicateSecretSyncDestinations  *bool               `json:"blockDuplicateSecretSyncDestinations,omitempty"`
			BypassOrgAuthEnabled                  *bool               `json:"bypassOrgAuthEnabled,omitempty"`
			CreatedAt                             time.Time           `json:"createdAt"`
			CustomerId                            *string             `json:"customerId"`
			DefaultMembershipRole                 *string             `json:"defaultMembershipRole,omitempty"`
			EnforceMfa                            *bool               `json:"enforceMfa,omitempty"`
			GoogleSsoAuthEnforced                 *bool               `json:"googleSsoAuthEnforced,omitempty"`
			GoogleSsoAuthLastUsed                 *time.Time          `json:"googleSsoAuthLastUsed"`
			Id                                    openapi_types.UUID  `json:"id"`
			KmsDefaultKeyId                       *openapi_types.UUID `json:"kmsDefaultKeyId"`
			KmsEncryptedDataKey                   interface{}         `json:"kmsEncryptedDataKey"`
			KmsProductEnabled                     *bool               `json:"kmsProductEnabled"`
			MaxSharedSecretLifetime               *float32            `json:"maxSharedSecretLifetime"`
			MaxSharedSecretViewLimit              *float32            `json:"maxSharedSecretViewLimit"`
			Name                                  string              `json:"name"`
			ParentOrgId                           *openapi_types.UUID `json:"parentOrgId"`
			PkiProductEnabled                     *bool               `json:"pkiProductEnabled"`
			PrivilegeUpgradeInitiatedAt           *time.Time          `json:"privilegeUpgradeInitiatedAt"`
			PrivilegeUpgradeInitiatedByUsername   *string             `json:"privilegeUpgradeInitiatedByUsername"`
			RootOrgId                             *openapi_types.UUID `json:"rootOrgId"`
			ScannerProductEnabled                 *bool               `json:"scannerProductEnabled"`
			ScimEnabled                           *bool               `json:"scimEnabled"`
			SecretsProductEnabled                 *bool               `json:"secretsProductEnabled"`
			SelectedMfaMethod                     *string             `json:"selectedMfaMethod"`
			ShareSecretsProductEnabled            *bool               `json:"shareSecretsProductEnabled"`
			ShouldUseNewPrivilegeSystem           *bool               `json:"shouldUseNewPrivilegeSystem,omitempty"`
			Slug                                  string              `json:"slug"`
			SshProductEnabled                     *bool               `json:"sshProductEnabled"`
			UpdatedAt                             time.Time           `json:"updatedAt"`
			UserTokenExpiration                   *string             `json:"userTokenExpiration"`
		} `json:"organization"`
		Token string `json:"token"`
		User  struct {
			AuthMethods                       *[]string          `json:"authMethods"`
			ConsecutiveFailedMfaAttempts      *float32           `json:"consecutiveFailedMfaAttempts"`
			ConsecutiveFailedPasswordAttempts *float32           `json:"consecutiveFailedPasswordAttempts"`
			CreatedAt                         time.Time          `json:"createdAt"`
			Devices                           interface{}        `json:"devices"`
			Email                             *string            `json:"email"`
			FirstName                         *string            `json:"firstName"`
			Id                                openapi_types.UUID `json:"id"`
			IsAccepted                        *bool              `json:"isAccepted"`
			IsEmailVerified                   *bool              `json:"isEmailVerified"`
			IsGhost                           *bool              `json:"isGhost,omitempty"`
			IsLocked                          *bool              `json:"isLocked"`
			IsMfaEnabled                      *bool              `json:"isMfaEnabled"`
			LastName                          *string            `json:"lastName"`
			MfaMethods                        *[]string          `json:"mfaMethods"`
			SelectedMfaMethod                 *string            `json:"selectedMfaMethod"`
			SuperAdmin                        *bool              `json:"superAdmin"`
			TemporaryLockDateEnd              *time.Time         `json:"temporaryLockDateEnd"`
			UpdatedAt                         time.Time          `json:"updatedAt"`
			Username                          string             `json:"username"`
		} `json:"user"`
	}
	JSON400 *struct {
		Error      string                            `json:"error"`
		Message    string                            `json:"message"`
		ReqId      string                            `json:"reqId"`
		StatusCode PostApiV1AdminSignup400StatusCode `json:"statusCode"`
	}
	JSON401 *struct {
		Error      string                            `json:"error"`
		Message    string                            `json:"message"`
		ReqId      string                            `json:"reqId"`
		StatusCode PostApiV1AdminSignup401StatusCode `json:"statusCode"`
	}
	JSON403 *struct {
		Details    interface{}                       `json:"details,omitempty"`
		Error      string                            `json:"error"`
		Message    string                            `json:"message"`
		ReqId      string                            `json:"reqId"`
		StatusCode PostApiV1AdminSignup403StatusCode `json:"statusCode"`
	}
	JSON404 *struct {
		Error      string                            `json:"error"`
		Message    string                            `json:"message"`
		ReqId      string                            `json:"reqId"`
		StatusCode PostApiV1AdminSignup404StatusCode `json:"statusCode"`
	}
	JSON422 *struct {
		Error      string                            `json:"error"`
		Message    interface{}                       `json:"message,omitempty"`
		ReqId      string                            `json:"reqId"`
		StatusCode PostApiV1AdminSignup422StatusCode `json:"statusCode"`
	}
	JSON500 *struct {
		Error      string                            `json:"error"`
		Message    string                            `json:"message"`
		ReqId      string                            `json:"reqId"`
		StatusCode PostApiV1AdminSignup500StatusCode `json:"statusCode"`
	}
}
type PostApiV1AdminSignup400StatusCode float32
type PostApiV1AdminSignup401StatusCode float32
type PostApiV1AdminSignup403StatusCode float32
type PostApiV1AdminSignup404StatusCode float32
type PostApiV1AdminSignup422StatusCode float32
type PostApiV1AdminSignup500StatusCode float32

// Status returns HTTPResponse.Status
func (r PostApiV1AdminSignupResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostApiV1AdminSignupResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostApiV1AuthTokenResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		OrganizationId *string `json:"organizationId,omitempty"`
		Token          string  `json:"token"`
	}
	JSON400 *struct {
		Error      string                          `json:"error"`
		Message    string                          `json:"message"`
		ReqId      string                          `json:"reqId"`
		StatusCode PostApiV1AuthToken400StatusCode `json:"statusCode"`
	}
	JSON401 *struct {
		Error      string                          `json:"error"`
		Message    string                          `json:"message"`
		ReqId      string                          `json:"reqId"`
		StatusCode PostApiV1AuthToken401StatusCode `json:"statusCode"`
	}
	JSON403 *struct {
		Details    interface{}                     `json:"details,omitempty"`
		Error      string                          `json:"error"`
		Message    string                          `json:"message"`
		ReqId      string                          `json:"reqId"`
		StatusCode PostApiV1AuthToken403StatusCode `json:"statusCode"`
	}
	JSON404 *struct {
		Error      string                          `json:"error"`
		Message    string                          `json:"message"`
		ReqId      string                          `json:"reqId"`
		StatusCode PostApiV1AuthToken404StatusCode `json:"statusCode"`
	}
	JSON422 *struct {
		Error      string                          `json:"error"`
		Message    interface{}                     `json:"message,omitempty"`
		ReqId      string                          `json:"reqId"`
		StatusCode PostApiV1AuthToken422StatusCode `json:"statusCode"`
	}
	JSON500 *struct {
		Error      string                          `json:"error"`
		Message    string                          `json:"message"`
		ReqId      string                          `json:"reqId"`
		StatusCode PostApiV1AuthToken500StatusCode `json:"statusCode"`
	}
}
type PostApiV1AuthToken400StatusCode float32
type PostApiV1AuthToken401StatusCode float32
type PostApiV1AuthToken403StatusCode float32
type PostApiV1AuthToken404StatusCode float32
type PostApiV1AuthToken422StatusCode float32
type PostApiV1AuthToken500StatusCode float32

// Status returns HTTPResponse.Status
func (r PostApiV1AuthTokenResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostApiV1AuthTokenResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetApiV1ProjectsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Projects []struct {
			UnderscoreId           string    `json:"_id"`
			AuditLogsRetentionDays *float32  `json:"auditLogsRetentionDays"`
			AutoCapitalization     *bool     `json:"autoCapitalization"`
			CreatedAt              time.Time `json:"createdAt"`
			DefaultProduct         *string   `json:"defaultProduct"`
			Description            *string   `json:"description"`
			Environments           []struct {
				Id   string `json:"id"`
				Name string `json:"name"`
				Slug string `json:"slug"`
			} `json:"environments"`
			HasDeleteProtection *bool               `json:"hasDeleteProtection"`
			Id                  string              `json:"id"`
			KmsCertificateKeyId *openapi_types.UUID `json:"kmsCertificateKeyId"`
			Name                string              `json:"name"`
			OrgId               openapi_types.UUID  `json:"orgId"`
			PitVersionLimit     *float32            `json:"pitVersionLimit,omitempty"`
			Roles               *[]struct {
				CreatedAt   time.Time          `json:"createdAt"`
				Description *string            `json:"description"`
				Id          openapi_types.UUID `json:"id"`
				Name        string             `json:"name"`
				Permissions interface{}        `json:"permissions,omitempty"`
				ProjectId   string             `json:"projectId"`
				Slug        string             `json:"slug"`
				UpdatedAt   time.Time          `json:"updatedAt"`
				Version     *float32           `json:"version,omitempty"`
			} `json:"roles,omitempty"`
			SecretDetectionIgnoreValues *[]string `json:"secretDetectionIgnoreValues"`
			SecretSharing               *bool     `json:"secretSharing,omitempty"`
			ShowSnapshotsLegacy         *bool     `json:"showSnapshotsLegacy,omitempty"`
			Slug                        string    `json:"slug"`
			Type                        string    `json:"type"`
			UpdatedAt                   time.Time `json:"updatedAt"`
			UpgradeStatus               *string   `json:"upgradeStatus"`
			Version                     *float32  `json:"version,omitempty"`
		} `json:"projects"`
	}
	JSON400 *struct {
		Error      string                        `json:"error"`
		Message    string                        `json:"message"`
		ReqId      string                        `json:"reqId"`
		StatusCode GetApiV1Projects400StatusCode `json:"statusCode"`
	}
	JSON401 *struct {
		Error      string                        `json:"error"`
		Message    string                        `json:"message"`
		ReqId      string                        `json:"reqId"`
		StatusCode GetApiV1Projects401StatusCode `json:"statusCode"`
	}
	JSON403 *struct {
		Details    interface{}                   `json:"details,omitempty"`
		Error      string                        `json:"error"`
		Message    string                        `json:"message"`
		ReqId      string                        `json:"reqId"`
		StatusCode GetApiV1Projects403StatusCode `json:"statusCode"`
	}
	JSON404 *struct {
		Error      string                        `json:"error"`
		Message    string                        `json:"message"`
		ReqId      string                        `json:"reqId"`
		StatusCode GetApiV1Projects404StatusCode `json:"statusCode"`
	}
	JSON422 *struct {
		Error      string                        `json:"error"`
		Message    interface{}                   `json:"message,omitempty"`
		ReqId      string                        `json:"reqId"`
		StatusCode GetApiV1Projects422StatusCode `json:"statusCode"`
	}
	JSON500 *struct {
		Error      string                        `json:"error"`
		Message    string                        `json:"message"`
		ReqId      string                        `json:"reqId"`
		StatusCode GetApiV1Projects500StatusCode `json:"statusCode"`
	}
}
type GetApiV1Projects400StatusCode float32
type GetApiV1Projects401StatusCode float32
type GetApiV1Projects403StatusCode float32
type GetApiV1Projects404StatusCode float32
type GetApiV1Projects422StatusCode float32
type GetApiV1Projects500StatusCode float32

// Status returns HTTPResponse.Status
func (r GetApiV1ProjectsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiV1ProjectsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostApiV1ProjectsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Project struct {
			UnderscoreId           string    `json:"_id"`
			AuditLogsRetentionDays *float32  `json:"auditLogsRetentionDays"`
			AutoCapitalization     *bool     `json:"autoCapitalization"`
			CreatedAt              time.Time `json:"createdAt"`
			DefaultProduct         *string   `json:"defaultProduct"`
			Description            *string   `json:"description"`
			Environments           []struct {
				Id   string `json:"id"`
				Name string `json:"name"`
				Slug string `json:"slug"`
			} `json:"environments"`
			HasDeleteProtection         *bool               `json:"hasDeleteProtection"`
			Id                          string              `json:"id"`
			KmsCertificateKeyId         *openapi_types.UUID `json:"kmsCertificateKeyId"`
			Name                        string              `json:"name"`
			OrgId                       openapi_types.UUID  `json:"orgId"`
			PitVersionLimit             *float32            `json:"pitVersionLimit,omitempty"`
			SecretDetectionIgnoreValues *[]string           `json:"secretDetectionIgnoreValues"`
			SecretSharing               *bool               `json:"secretSharing,omitempty"`
			ShowSnapshotsLegacy         *bool               `json:"showSnapshotsLegacy,omitempty"`
			Slug                        string              `json:"slug"`
			Type                        string              `json:"type"`
			UpdatedAt                   time.Time           `json:"updatedAt"`
			UpgradeStatus               *string             `json:"upgradeStatus"`
			Version                     *float32            `json:"version,omitempty"`
		} `json:"project"`
	}
	JSON400 *struct {
		Error      string                         `json:"error"`
		Message    string                         `json:"message"`
		ReqId      string                         `json:"reqId"`
		StatusCode PostApiV1Projects400StatusCode `json:"statusCode"`
	}
	JSON401 *struct {
		Error      string                         `json:"error"`
		Message    string                         `json:"message"`
		ReqId      string                         `json:"reqId"`
		StatusCode PostApiV1Projects401StatusCode `json:"statusCode"`
	}
	JSON403 *struct {
		Details    interface{}                    `json:"details,omitempty"`
		Error      string                         `json:"error"`
		Message    string                         `json:"message"`
		ReqId      string                         `json:"reqId"`
		StatusCode PostApiV1Projects403StatusCode `json:"statusCode"`
	}
	JSON404 *struct {
		Error      string                         `json:"error"`
		Message    string                         `json:"message"`
		ReqId      string                         `json:"reqId"`
		StatusCode PostApiV1Projects404StatusCode `json:"statusCode"`
	}
	JSON422 *struct {
		Error      string                         `json:"error"`
		Message    interface{}                    `json:"message,omitempty"`
		ReqId      string                         `json:"reqId"`
		StatusCode PostApiV1Projects422StatusCode `json:"statusCode"`
	}
	JSON500 *struct {
		Error      string                         `json:"error"`
		Message    string                         `json:"message"`
		ReqId      string                         `json:"reqId"`
		StatusCode PostApiV1Projects500StatusCode `json:"statusCode"`
	}
}
type PostApiV1Projects400StatusCode float32
type PostApiV1Projects401StatusCode float32
type PostApiV1Projects403StatusCode float32
type PostApiV1Projects404StatusCode float32
type PostApiV1Projects422StatusCode float32
type PostApiV1Projects500StatusCode float32

// Status returns HTTPResponse.Status
func (r PostApiV1ProjectsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostApiV1ProjectsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostApiV3AuthSelectOrganizationResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		IsMfaEnabled bool    `json:"isMfaEnabled"`
		MfaMethod    *string `json:"mfaMethod,omitempty"`
		Token        string  `json:"token"`
	}
	JSON400 *struct {
		Error      string                                       `json:"error"`
		Message    string                                       `json:"message"`
		ReqId      string                                       `json:"reqId"`
		StatusCode PostApiV3AuthSelectOrganization400StatusCode `json:"statusCode"`
	}
	JSON401 *struct {
		Error      string                                       `json:"error"`
		Message    string                                       `json:"message"`
		ReqId      string                                       `json:"reqId"`
		StatusCode PostApiV3AuthSelectOrganization401StatusCode `json:"statusCode"`
	}
	JSON403 *struct {
		Details    interface{}                                  `json:"details,omitempty"`
		Error      string                                       `json:"error"`
		Message    string                                       `json:"message"`
		ReqId      string                                       `json:"reqId"`
		StatusCode PostApiV3AuthSelectOrganization403StatusCode `json:"statusCode"`
	}
	JSON404 *struct {
		Error      string                                       `json:"error"`
		Message    string                                       `json:"message"`
		ReqId      string                                       `json:"reqId"`
		StatusCode PostApiV3AuthSelectOrganization404StatusCode `json:"statusCode"`
	}
	JSON422 *struct {
		Error      string                                       `json:"error"`
		Message    interface{}                                  `json:"message,omitempty"`
		ReqId      string                                       `json:"reqId"`
		StatusCode PostApiV3AuthSelectOrganization422StatusCode `json:"statusCode"`
	}
	JSON500 *struct {
		Error      string                                       `json:"error"`
		Message    string                                       `json:"message"`
		ReqId      string                                       `json:"reqId"`
		StatusCode PostApiV3AuthSelectOrganization500StatusCode `json:"statusCode"`
	}
}
type PostApiV3AuthSelectOrganization400StatusCode float32
type PostApiV3AuthSelectOrganization401StatusCode float32
type PostApiV3AuthSelectOrganization403StatusCode float32
type PostApiV3AuthSelectOrganization404StatusCode float32
type PostApiV3AuthSelectOrganization422StatusCode float32
type PostApiV3AuthSelectOrganization500StatusCode float32

// Status returns HTTPResponse.Status
func (r PostApiV3AuthSelectOrganizationResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostApiV3AuthSelectOrganizationResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// PostApiV1AdminSignupWithBodyWithResponse request with arbitrary body returning *PostApiV1AdminSignupResponse
func (c *ClientWithResponses) PostApiV1AdminSignupWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiV1AdminSignupResponse, error) {
	rsp, err := c.PostApiV1AdminSignupWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiV1AdminSignupResponse(rsp)
}

func (c *ClientWithResponses) PostApiV1AdminSignupWithResponse(ctx context.Context, body PostApiV1AdminSignupJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiV1AdminSignupResponse, error) {
	rsp, err := c.PostApiV1AdminSignup(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiV1AdminSignupResponse(rsp)
}

// PostApiV1AuthTokenWithResponse request returning *PostApiV1AuthTokenResponse
func (c *ClientWithResponses) PostApiV1AuthTokenWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*PostApiV1AuthTokenResponse, error) {
	rsp, err := c.PostApiV1AuthToken(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiV1AuthTokenResponse(rsp)
}

// GetApiV1ProjectsWithResponse request returning *GetApiV1ProjectsResponse
func (c *ClientWithResponses) GetApiV1ProjectsWithResponse(ctx context.Context, params *GetApiV1ProjectsParams, reqEditors ...RequestEditorFn) (*GetApiV1ProjectsResponse, error) {
	rsp, err := c.GetApiV1Projects(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiV1ProjectsResponse(rsp)
}

// PostApiV1ProjectsWithBodyWithResponse request with arbitrary body returning *PostApiV1ProjectsResponse
func (c *ClientWithResponses) PostApiV1ProjectsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiV1ProjectsResponse, error) {
	rsp, err := c.PostApiV1ProjectsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiV1ProjectsResponse(rsp)
}

func (c *ClientWithResponses) PostApiV1ProjectsWithResponse(ctx context.Context, body PostApiV1ProjectsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiV1ProjectsResponse, error) {
	rsp, err := c.PostApiV1Projects(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiV1ProjectsResponse(rsp)
}

// PostApiV3AuthSelectOrganizationWithBodyWithResponse request with arbitrary body returning *PostApiV3AuthSelectOrganizationResponse
func (c *ClientWithResponses) PostApiV3AuthSelectOrganizationWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiV3AuthSelectOrganizationResponse, error) {
	rsp, err := c.PostApiV3AuthSelectOrganizationWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiV3AuthSelectOrganizationResponse(rsp)
}

func (c *ClientWithResponses) PostApiV3AuthSelectOrganizationWithResponse(ctx context.Context, body PostApiV3AuthSelectOrganizationJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiV3AuthSelectOrganizationResponse, error) {
	rsp, err := c.PostApiV3AuthSelectOrganization(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiV3AuthSelectOrganizationResponse(rsp)
}

// ParsePostApiV1AdminSignupResponse parses an HTTP response from a PostApiV1AdminSignupWithResponse call
func ParsePostApiV1AdminSignupResponse(rsp *http.Response) (*PostApiV1AdminSignupResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostApiV1AdminSignupResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Message      string `json:"message"`
			New          string `json:"new"`
			Organization struct {
				AllowSecretSharingOutsideOrganization *bool               `json:"allowSecretSharingOutsideOrganization"`
				AuthEnforced                          *bool               `json:"authEnforced"`
				BlockDuplicateSecretSyncDestinations  *bool               `json:"blockDuplicateSecretSyncDestinations,omitempty"`
				BypassOrgAuthEnabled                  *bool               `json:"bypassOrgAuthEnabled,omitempty"`
				CreatedAt                             time.Time           `json:"createdAt"`
				CustomerId                            *string             `json:"customerId"`
				DefaultMembershipRole                 *string             `json:"defaultMembershipRole,omitempty"`
				EnforceMfa                            *bool               `json:"enforceMfa,omitempty"`
				GoogleSsoAuthEnforced                 *bool               `json:"googleSsoAuthEnforced,omitempty"`
				GoogleSsoAuthLastUsed                 *time.Time          `json:"googleSsoAuthLastUsed"`
				Id                                    openapi_types.UUID  `json:"id"`
				KmsDefaultKeyId                       *openapi_types.UUID `json:"kmsDefaultKeyId"`
				KmsEncryptedDataKey                   interface{}         `json:"kmsEncryptedDataKey"`
				KmsProductEnabled                     *bool               `json:"kmsProductEnabled"`
				MaxSharedSecretLifetime               *float32            `json:"maxSharedSecretLifetime"`
				MaxSharedSecretViewLimit              *float32            `json:"maxSharedSecretViewLimit"`
				Name                                  string              `json:"name"`
				ParentOrgId                           *openapi_types.UUID `json:"parentOrgId"`
				PkiProductEnabled                     *bool               `json:"pkiProductEnabled"`
				PrivilegeUpgradeInitiatedAt           *time.Time          `json:"privilegeUpgradeInitiatedAt"`
				PrivilegeUpgradeInitiatedByUsername   *string             `json:"privilegeUpgradeInitiatedByUsername"`
				RootOrgId                             *openapi_types.UUID `json:"rootOrgId"`
				ScannerProductEnabled                 *bool               `json:"scannerProductEnabled"`
				ScimEnabled                           *bool               `json:"scimEnabled"`
				SecretsProductEnabled                 *bool               `json:"secretsProductEnabled"`
				SelectedMfaMethod                     *string             `json:"selectedMfaMethod"`
				ShareSecretsProductEnabled            *bool               `json:"shareSecretsProductEnabled"`
				ShouldUseNewPrivilegeSystem           *bool               `json:"shouldUseNewPrivilegeSystem,omitempty"`
				Slug                                  string              `json:"slug"`
				SshProductEnabled                     *bool               `json:"sshProductEnabled"`
				UpdatedAt                             time.Time           `json:"updatedAt"`
				UserTokenExpiration                   *string             `json:"userTokenExpiration"`
			} `json:"organization"`
			Token string `json:"token"`
			User  struct {
				AuthMethods                       *[]string          `json:"authMethods"`
				ConsecutiveFailedMfaAttempts      *float32           `json:"consecutiveFailedMfaAttempts"`
				ConsecutiveFailedPasswordAttempts *float32           `json:"consecutiveFailedPasswordAttempts"`
				CreatedAt                         time.Time          `json:"createdAt"`
				Devices                           interface{}        `json:"devices"`
				Email                             *string            `json:"email"`
				FirstName                         *string            `json:"firstName"`
				Id                                openapi_types.UUID `json:"id"`
				IsAccepted                        *bool              `json:"isAccepted"`
				IsEmailVerified                   *bool              `json:"isEmailVerified"`
				IsGhost                           *bool              `json:"isGhost,omitempty"`
				IsLocked                          *bool              `json:"isLocked"`
				IsMfaEnabled                      *bool              `json:"isMfaEnabled"`
				LastName                          *string            `json:"lastName"`
				MfaMethods                        *[]string          `json:"mfaMethods"`
				SelectedMfaMethod                 *string            `json:"selectedMfaMethod"`
				SuperAdmin                        *bool              `json:"superAdmin"`
				TemporaryLockDateEnd              *time.Time         `json:"temporaryLockDateEnd"`
				UpdatedAt                         time.Time          `json:"updatedAt"`
				Username                          string             `json:"username"`
			} `json:"user"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest struct {
			Error      string                            `json:"error"`
			Message    string                            `json:"message"`
			ReqId      string                            `json:"reqId"`
			StatusCode PostApiV1AdminSignup400StatusCode `json:"statusCode"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest struct {
			Error      string                            `json:"error"`
			Message    string                            `json:"message"`
			ReqId      string                            `json:"reqId"`
			StatusCode PostApiV1AdminSignup401StatusCode `json:"statusCode"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest struct {
			Details    interface{}                       `json:"details,omitempty"`
			Error      string                            `json:"error"`
			Message    string                            `json:"message"`
			ReqId      string                            `json:"reqId"`
			StatusCode PostApiV1AdminSignup403StatusCode `json:"statusCode"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest struct {
			Error      string                            `json:"error"`
			Message    string                            `json:"message"`
			ReqId      string                            `json:"reqId"`
			StatusCode PostApiV1AdminSignup404StatusCode `json:"statusCode"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest struct {
			Error      string                            `json:"error"`
			Message    interface{}                       `json:"message,omitempty"`
			ReqId      string                            `json:"reqId"`
			StatusCode PostApiV1AdminSignup422StatusCode `json:"statusCode"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest struct {
			Error      string                            `json:"error"`
			Message    string                            `json:"message"`
			ReqId      string                            `json:"reqId"`
			StatusCode PostApiV1AdminSignup500StatusCode `json:"statusCode"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePostApiV1AuthTokenResponse parses an HTTP response from a PostApiV1AuthTokenWithResponse call
func ParsePostApiV1AuthTokenResponse(rsp *http.Response) (*PostApiV1AuthTokenResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostApiV1AuthTokenResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			OrganizationId *string `json:"organizationId,omitempty"`
			Token          string  `json:"token"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest struct {
			Error      string                          `json:"error"`
			Message    string                          `json:"message"`
			ReqId      string                          `json:"reqId"`
			StatusCode PostApiV1AuthToken400StatusCode `json:"statusCode"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest struct {
			Error      string                          `json:"error"`
			Message    string                          `json:"message"`
			ReqId      string                          `json:"reqId"`
			StatusCode PostApiV1AuthToken401StatusCode `json:"statusCode"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest struct {
			Details    interface{}                     `json:"details,omitempty"`
			Error      string                          `json:"error"`
			Message    string                          `json:"message"`
			ReqId      string                          `json:"reqId"`
			StatusCode PostApiV1AuthToken403StatusCode `json:"statusCode"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest struct {
			Error      string                          `json:"error"`
			Message    string                          `json:"message"`
			ReqId      string                          `json:"reqId"`
			StatusCode PostApiV1AuthToken404StatusCode `json:"statusCode"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest struct {
			Error      string                          `json:"error"`
			Message    interface{}                     `json:"message,omitempty"`
			ReqId      string                          `json:"reqId"`
			StatusCode PostApiV1AuthToken422StatusCode `json:"statusCode"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest struct {
			Error      string                          `json:"error"`
			Message    string                          `json:"message"`
			ReqId      string                          `json:"reqId"`
			StatusCode PostApiV1AuthToken500StatusCode `json:"statusCode"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetApiV1ProjectsResponse parses an HTTP response from a GetApiV1ProjectsWithResponse call
func ParseGetApiV1ProjectsResponse(rsp *http.Response) (*GetApiV1ProjectsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiV1ProjectsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Projects []struct {
				UnderscoreId           string    `json:"_id"`
				AuditLogsRetentionDays *float32  `json:"auditLogsRetentionDays"`
				AutoCapitalization     *bool     `json:"autoCapitalization"`
				CreatedAt              time.Time `json:"createdAt"`
				DefaultProduct         *string   `json:"defaultProduct"`
				Description            *string   `json:"description"`
				Environments           []struct {
					Id   string `json:"id"`
					Name string `json:"name"`
					Slug string `json:"slug"`
				} `json:"environments"`
				HasDeleteProtection *bool               `json:"hasDeleteProtection"`
				Id                  string              `json:"id"`
				KmsCertificateKeyId *openapi_types.UUID `json:"kmsCertificateKeyId"`
				Name                string              `json:"name"`
				OrgId               openapi_types.UUID  `json:"orgId"`
				PitVersionLimit     *float32            `json:"pitVersionLimit,omitempty"`
				Roles               *[]struct {
					CreatedAt   time.Time          `json:"createdAt"`
					Description *string            `json:"description"`
					Id          openapi_types.UUID `json:"id"`
					Name        string             `json:"name"`
					Permissions interface{}        `json:"permissions,omitempty"`
					ProjectId   string             `json:"projectId"`
					Slug        string             `json:"slug"`
					UpdatedAt   time.Time          `json:"updatedAt"`
					Version     *float32           `json:"version,omitempty"`
				} `json:"roles,omitempty"`
				SecretDetectionIgnoreValues *[]string `json:"secretDetectionIgnoreValues"`
				SecretSharing               *bool     `json:"secretSharing,omitempty"`
				ShowSnapshotsLegacy         *bool     `json:"showSnapshotsLegacy,omitempty"`
				Slug                        string    `json:"slug"`
				Type                        string    `json:"type"`
				UpdatedAt                   time.Time `json:"updatedAt"`
				UpgradeStatus               *string   `json:"upgradeStatus"`
				Version                     *float32  `json:"version,omitempty"`
			} `json:"projects"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest struct {
			Error      string                        `json:"error"`
			Message    string                        `json:"message"`
			ReqId      string                        `json:"reqId"`
			StatusCode GetApiV1Projects400StatusCode `json:"statusCode"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest struct {
			Error      string                        `json:"error"`
			Message    string                        `json:"message"`
			ReqId      string                        `json:"reqId"`
			StatusCode GetApiV1Projects401StatusCode `json:"statusCode"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest struct {
			Details    interface{}                   `json:"details,omitempty"`
			Error      string                        `json:"error"`
			Message    string                        `json:"message"`
			ReqId      string                        `json:"reqId"`
			StatusCode GetApiV1Projects403StatusCode `json:"statusCode"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest struct {
			Error      string                        `json:"error"`
			Message    string                        `json:"message"`
			ReqId      string                        `json:"reqId"`
			StatusCode GetApiV1Projects404StatusCode `json:"statusCode"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest struct {
			Error      string                        `json:"error"`
			Message    interface{}                   `json:"message,omitempty"`
			ReqId      string                        `json:"reqId"`
			StatusCode GetApiV1Projects422StatusCode `json:"statusCode"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest struct {
			Error      string                        `json:"error"`
			Message    string                        `json:"message"`
			ReqId      string                        `json:"reqId"`
			StatusCode GetApiV1Projects500StatusCode `json:"statusCode"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePostApiV1ProjectsResponse parses an HTTP response from a PostApiV1ProjectsWithResponse call
func ParsePostApiV1ProjectsResponse(rsp *http.Response) (*PostApiV1ProjectsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostApiV1ProjectsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Project struct {
				UnderscoreId           string    `json:"_id"`
				AuditLogsRetentionDays *float32  `json:"auditLogsRetentionDays"`
				AutoCapitalization     *bool     `json:"autoCapitalization"`
				CreatedAt              time.Time `json:"createdAt"`
				DefaultProduct         *string   `json:"defaultProduct"`
				Description            *string   `json:"description"`
				Environments           []struct {
					Id   string `json:"id"`
					Name string `json:"name"`
					Slug string `json:"slug"`
				} `json:"environments"`
				HasDeleteProtection         *bool               `json:"hasDeleteProtection"`
				Id                          string              `json:"id"`
				KmsCertificateKeyId         *openapi_types.UUID `json:"kmsCertificateKeyId"`
				Name                        string              `json:"name"`
				OrgId                       openapi_types.UUID  `json:"orgId"`
				PitVersionLimit             *float32            `json:"pitVersionLimit,omitempty"`
				SecretDetectionIgnoreValues *[]string           `json:"secretDetectionIgnoreValues"`
				SecretSharing               *bool               `json:"secretSharing,omitempty"`
				ShowSnapshotsLegacy         *bool               `json:"showSnapshotsLegacy,omitempty"`
				Slug                        string              `json:"slug"`
				Type                        string              `json:"type"`
				UpdatedAt                   time.Time           `json:"updatedAt"`
				UpgradeStatus               *string             `json:"upgradeStatus"`
				Version                     *float32            `json:"version,omitempty"`
			} `json:"project"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest struct {
			Error      string                         `json:"error"`
			Message    string                         `json:"message"`
			ReqId      string                         `json:"reqId"`
			StatusCode PostApiV1Projects400StatusCode `json:"statusCode"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest struct {
			Error      string                         `json:"error"`
			Message    string                         `json:"message"`
			ReqId      string                         `json:"reqId"`
			StatusCode PostApiV1Projects401StatusCode `json:"statusCode"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest struct {
			Details    interface{}                    `json:"details,omitempty"`
			Error      string                         `json:"error"`
			Message    string                         `json:"message"`
			ReqId      string                         `json:"reqId"`
			StatusCode PostApiV1Projects403StatusCode `json:"statusCode"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest struct {
			Error      string                         `json:"error"`
			Message    string                         `json:"message"`
			ReqId      string                         `json:"reqId"`
			StatusCode PostApiV1Projects404StatusCode `json:"statusCode"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest struct {
			Error      string                         `json:"error"`
			Message    interface{}                    `json:"message,omitempty"`
			ReqId      string                         `json:"reqId"`
			StatusCode PostApiV1Projects422StatusCode `json:"statusCode"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest struct {
			Error      string                         `json:"error"`
			Message    string                         `json:"message"`
			ReqId      string                         `json:"reqId"`
			StatusCode PostApiV1Projects500StatusCode `json:"statusCode"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePostApiV3AuthSelectOrganizationResponse parses an HTTP response from a PostApiV3AuthSelectOrganizationWithResponse call
func ParsePostApiV3AuthSelectOrganizationResponse(rsp *http.Response) (*PostApiV3AuthSelectOrganizationResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostApiV3AuthSelectOrganizationResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			IsMfaEnabled bool    `json:"isMfaEnabled"`
			MfaMethod    *string `json:"mfaMethod,omitempty"`
			Token        string  `json:"token"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest struct {
			Error      string                                       `json:"error"`
			Message    string                                       `json:"message"`
			ReqId      string                                       `json:"reqId"`
			StatusCode PostApiV3AuthSelectOrganization400StatusCode `json:"statusCode"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest struct {
			Error      string                                       `json:"error"`
			Message    string                                       `json:"message"`
			ReqId      string                                       `json:"reqId"`
			StatusCode PostApiV3AuthSelectOrganization401StatusCode `json:"statusCode"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest struct {
			Details    interface{}                                  `json:"details,omitempty"`
			Error      string                                       `json:"error"`
			Message    string                                       `json:"message"`
			ReqId      string                                       `json:"reqId"`
			StatusCode PostApiV3AuthSelectOrganization403StatusCode `json:"statusCode"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest struct {
			Error      string                                       `json:"error"`
			Message    string                                       `json:"message"`
			ReqId      string                                       `json:"reqId"`
			StatusCode PostApiV3AuthSelectOrganization404StatusCode `json:"statusCode"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest struct {
			Error      string                                       `json:"error"`
			Message    interface{}                                  `json:"message,omitempty"`
			ReqId      string                                       `json:"reqId"`
			StatusCode PostApiV3AuthSelectOrganization422StatusCode `json:"statusCode"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest struct {
			Error      string                                       `json:"error"`
			Message    string                                       `json:"message"`
			ReqId      string                                       `json:"reqId"`
			StatusCode PostApiV3AuthSelectOrganization500StatusCode `json:"statusCode"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}
